name: CI

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "0 7 * * 1"
  push:
    branches:
      - "master"
      - "develop"
      - "feature/**"
      - "bugfix/**"
      - "hotfix/**"
      - "support/**"
    paths:
      - "bin/**.c"
      - "lib/**.c"
      - "test/**.c"
  pull_request:
    branches:
      - "master"
      - "develop"
      - "feature/**"
      - "bugfix/**"
      - "hotfix/**"
      - "support/**"
    paths:
      - "bin/**.c"
      - "lib/**.c"
      - "test/**.c"

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Install dependencies
        run: sudo apt-get install cmake

      - name: Run clang-format
        run: |
          find lib -iname *.h -o -iname *.c | xargs clang-format -i
          git diff --exit-code

      - name: Run tests
        run: |
          make test
